### ISSUE TITLE
suggested addition to your .gitignore

### ISSUE THREAD

**Issue by tofr** [hunter-teacher-cert/summer-2020-assignments-jhans404#2]
Greetings Joshua:

I see this in your repo, and think you probably don't want to track it:
`.DS_Store`

If you add these lines to your `.gitignore` file, it will explicitly not track files like this (ie those that are auto-generated by your OS, etc):

```
# BOSS XTRAS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Text Backup Files #
*.s[a-w][a-z]
*~
\#*\#
.\#*

# OS X Files #
.DS_Store
._*
_*
.Spotlight*
.Trashes

# Windows Files #
Thumbs.db
ehthumbs.db

# Filenames with special characters
**/*[\\/\:;*?!'"<>|$º•¶§∞¢£]*
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

You can also copy my entire .gitignore over to your repo if you like. It is here:
https://raw.githubusercontent.com/hunter-teacher-cert/summer-2020-assignments-tofr/master/.gitignore

...and if you find this useful, do share with the rest of the crew.

**Comment by jhans404** [comment]
thanks, i think it should be working now!
